### ISSUE TITLE
Remove __tests__ folder for more consistency with the new default RN template

### ISSUE THREAD

**Issue by emin93** [emin93/react-native-template-typescript#13]

**Comment by emin93** [comment]
This seems more like an issue on the React Native CLI side. I just checked the default React Native template still has the __tests__ folder: https://github.com/facebook/react-native/tree/master/local-cli/templates/HelloWorld/__tests__

**Comment by sinewave440hz** [comment]
For reference, yes, this is a regression issue described here: https://github.com/facebook/react-native/issues/19761
