### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by theapache64** [emin93/react-native-template-typescript#19]
Cool one, perfectly working, good work. (y)

Although I've one about the working of this system.  How does the command 'react-native init MyApp **--template typescript**' connects to this github repo ? Is this published in any official **react native things** server ? or the RN system installs 'yarn add react-native-template-**anything-after-template-flag**' ?

**Comment by emin93** [comment]
Hi @theapache64,

Thank you for the kind words.

I'd like to make this a more understandable to you: It's just a naming pattern the React Native CLI uses to look up for templates on NPM. Every package that is prefixed with `react-native-template-` can be used in the CLI.

Here's a great article about the full template functionality in the CLI: https://medium.com/dailyjs/the-1-2-3s-of-react-native-templates-1f5dda037e11

Actually pretty simple. 😄

I'm going to close this issue as it's a general React Native CLI question and not fully related to this template.
