### ISSUE TITLE
Use react-native-typescript-transformer

### ISSUE THREAD

**Issue by emin93** [emin93/react-native-template-typescript#2]

**Comment by tednyberg** [comment]
Not sure why this was closed, I'm guessing without this the project template only sets up Babel to let Babel handle transpiling TypeScript?

I would propose including react-native-typescript-transformer by default in `metro.config.js` regardless. For example, I had problems with _namespaces_ in TypeScript before finding some comment in some repo mentioning this configuration option. :)

**Comment by emin93** [comment]
Sorry for my delayed answer. This issue has been closed because it has been included, but then RN 0.57 came out which introduced Babel and made the TS transformer for most cases obsolete (more info here: https://github.com/ds300/react-native-typescript-transformer). If you'd still like to use the TS transformer, you can still do that, just follow the instructions in the Transformer repo.
