### ISSUE TITLE
Not working with Hello World tests

### ISSUE THREAD

**Issue by jpdriver** [emin93/react-native-template-typescript#20]
## Expected results

The [Hello World test](https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/__tests__/App.js) should pass

## Observed results

Something about the Babel / Jest config isn't working

### Logs

```
> Typescript@0.0.1 test /Users/jp/Sites/Typescript
> jest

 FAIL  __tests__/App.tsx
  ● Test suite failed to run

    Plugin 0 specified in "/Users/jp/Sites/Typescript/node_modules/babel-preset-react-native/index.js" provided an invalid property of "default" (While processing preset: "/Users/jp/Sites/Typescript/node_modules/babel-preset-react-native/index.js")

      at Plugin.init (node_modules/babel-core/lib/transformation/plugin.js:131:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.576s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Typescript@0.0.1 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Typescript@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
## Steps to reproduce

1. Run `react-native init app --template typescript`

2. Make a new `__tests__` directory in the root

3. Copy `__tests__/App.js` from [the Hello World template](https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/__tests__/App.js) and save it as `__tests__/App.tsx`

4. Run `npm test`

**Comment by emin93** [comment]
Hi @jpdriver,

Thank you for opening the issue. I'm closely following the React Native releases and issues to keep this template always up to date. I know for a fact that this also doesn't work on React Native projects without TypeScript. There's already an open issue about it: https://github.com/facebook/react-native/issues/19859

This means it's not directly related to this template and that's why I'm going to close the issue. Let's hope it gets fixed with the next version (https://github.com/react-native-community/react-native-releases/issues/34#issuecomment-414220393).

I hope this will help you.

Cheers,
Emin

**Comment by jpdriver** [comment]
Yep, totally fair. Thanks for the quick response!
