### ISSUE TITLE
Make it possible to write tests in TypeScript

### ISSUE THREAD

**Issue by JReinhold** [emin93/react-native-template-typescript#26]
## Expected results

That configurations exists to make it possible to write tests with TypeScript. I'm aware that there exists some guide out there that allows us to configure Jest to work with TypeScript, but I think it should be part of this awesome template from the beginning.

## Observed results

Currently the test that is created with this template is written in JS, and converting them to TypeScript makes Jest crash.

### Logs

```
> yarn test
yarn run v1.13.0
$ jest
 FAIL  __tests__/App.tsx
  ● Test suite failed to run

    MyTSApp/__tests__/App.tsx:6
    import 'react-native';
           ^^^^^^^^^^^^^^

    SyntaxError: Unexpected string

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.206s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to reproduce

1. `react-native init MyTSApp --template typescript && node MyTSApp/setup.js`
2. Rename `__tests__/App.js` to `__tests__/App.tsx`
3. Get error about invalid syntax (see error above)

**Comment by emin93** [comment]
Hi @JReinhold,

Thank you for taking the time to create the issue. To be honest, I was convinced that with the new version of React Native (0.57+) there would be no need for ts-jest, but apparently I was wrong. I will add it again and release a new version.

I apologize for the inconvenience.

**Comment by JReinhold** [comment]
I understand your confusion, I actually thought the same thing. No worries, have a nice day!

**Comment by emin93** [comment]
Quick update: It seems like in the latest RN version (0.59.0-rc.3) TypeScript testing also works without `ts-jest`. I am preparing the changes in a separate branch for the upcoming release.
